pom.xml
https://issues.redhat.com/browse/DBZ-2636
=> DBZ-2636 Update pom to be compatible with release process

README.md
@gunnarmorling A quick fix here :) 
https://issues.redhat.com/browse/DBZ-2802
=> DBZ-2802 Fix build status badge in README.md

README.md
for review & merge once https://github.com/debezium/debezium-examples/pull/139 will be merged
=> DBZ-1463 Add "Getting Started" Section

src/main/java/io/debezium/connector/cassandra/CellData.java, src/main/java/io/debezium/connector/cassandra/transforms/type/deserializer/DurationTypeDeserializer.java, src/main/java/io/debezium/connector/cassandra/transforms/type/deserializer/InetAddressDeserializer.java, src/main/java/io/debezium/connector/cassandra/transforms/type/deserializer/ListTypeDeserializer.java, src/main/java/io/debezium/connector/cassandra/transforms/type/deserializer/LogicalTypeDeserializer.java, src/main/java/io/debezium/connector/cassandra/transforms/type/deserializer/MapTypeDeserializer.java, src/main/java/io/debezium/connector/cassandra/transforms/type/deserializer/SetTypeDeserializer.java, src/main/java/io/debezium/connector/cassandra/transforms/type/deserializer/TimeUUIDTypeDeserializer.java, src/main/java/io/debezium/connector/cassandra/transforms/type/deserializer/TimestampTypeDeserializer.java, src/main/java/io/debezium/connector/cassandra/transforms/type/deserializer/UUIDTypeDeserializer.java, src/main/java/io/debezium/connector/cassandra/transforms/type/deserializer/UserTypeDeserializer.java, src/test/java/io/debezium/connector/cassandra/transforms/CassandraTypeDeserializerTest.java
https://issues.redhat.com/browse/DBZ-2974
=> [DBZ-2974]: Fix deserialization of List<UserType> columns

README.md
https://issues.redhat.com/browse/DBZ-2901
=> DBZ-2901 Update README for building Debezium locally before running non-core repos

.github/workflows/maven.yml
https://issues.redhat.com/browse/DBZ-3012
=> DBZ-3012 Ignore .md files upon CI build

.github/workflows/maven.yml
@gunnarmorling minor fix here.
=> DBZ-3012 Fix Indentation

src/main/java/io/debezium/connector/cassandra/AbstractProcessor.java, src/main/java/io/debezium/connector/cassandra/CassandraConnectorConfig.java, src/main/java/io/debezium/connector/cassandra/CassandraConnectorContext.java, src/main/java/io/debezium/connector/cassandra/CommitLogPostProcessor.java, src/main/java/io/debezium/connector/cassandra/CommitLogProcessor.java, src/main/java/io/debezium/connector/cassandra/QueueProcessor.java, src/main/java/io/debezium/connector/cassandra/SchemaProcessor.java, src/main/java/io/debezium/connector/cassandra/SnapshotProcessor.java, src/test/java/io/debezium/connector/cassandra/CassandraConnectorConfigTest.java, src/test/java/io/debezium/connector/cassandra/CassandraConnectorTaskTest.java
https://issues.redhat.com/browse/DBZ-3063
@bingqinzhou, quick follow-up to your PR; could you review and merge if it's ok? Thx!
=> DBZ-3063 Using Duration more consistently

src/main/java/io/debezium/connector/cassandra/CassandraConnectorContext.java, src/main/java/io/debezium/connector/cassandra/CommitLogProcessor.java, src/main/java/io/debezium/connector/cassandra/EOFEvent.java, src/main/java/io/debezium/connector/cassandra/KafkaRecordEmitter.java, src/main/java/io/debezium/connector/cassandra/QueueProcessor.java, src/main/java/io/debezium/connector/cassandra/transforms/CassandraTypeDeserializer.java, src/main/java/io/debezium/connector/cassandra/transforms/type/deserializer/ListTypeDeserializer.java, src/main/java/io/debezium/connector/cassandra/transforms/type/deserializer/MapTypeDeserializer.java, src/main/java/io/debezium/connector/cassandra/transforms/type/deserializer/SetTypeDeserializer.java, src/main/java/io/debezium/connector/cassandra/transforms/type/deserializer/UserDefinedTypeDeserializer.java, src/test/java/io/debezium/connector/cassandra/CommitLogProcessorTest.java, src/test/java/io/debezium/connector/cassandra/QueueProcessorTest.java
https://issues.redhat.com/browse/DBZ-3224
=> [DBZ-3224] Improve error handling logic when failing to publish change events.

src/main/resources/log4j.properties
Add log4j.properties file to debezium cassandra connector
=> DBZ-3248 add log4j.properties file

.github/workflows/maven.yml, pom.xml
https://issues.redhat.com/browse/DBZ-2870
=> DBZ-2870 Enforce Java 8

.github/workflows/maven.yml, README.md, pom.xml
https://issues.redhat.com/browse/DBZ-3449
=> DBZ-3449 Adding 'quick' profile

.github/workflows/cross-maven.yml, .github/workflows/maven.yml
https://issues.redhat.com/browse/DBZ-3748
=> DBZ-3748 Cross CI cassandra build on pull request event with debezium core repository

src/main/java/io/debezium/connector/cassandra/transforms/type/deserializer/UUIDTypeDeserializer.java, src/test/java/io/debezium/connector/cassandra/transforms/CassandraTypeDeserializerTest.java
change UUID representation from base64 encoding to standard string.
=> DBZ-3885 change UUID handling

src/test/java/io/debezium/connector/cassandra/CassandraConnectorConfigTest.java, src/test/java/io/debezium/connector/cassandra/FileOffsetWriterTest.java, src/test/java/io/debezium/connector/cassandra/QueueProcessorTest.java
https://issues.redhat.com/browse/DBZ-4077
=> DBZ-4077 Adjusting to required logical name attribute

src/main/java/io/debezium/connector/cassandra/CassandraSourceInfoStructMaker.java
See [DBZ-3535](https://issues.redhat.com/browse/DBZ-3535).
This PR complements https://github.com/debezium/debezium/pull/3309.
=> DBZ-3535: Introduce schema.name.adjustment.mode

core/src/main/java/io/debezium/connector/cassandra/CassandraConnectorConfig.java, core/src/test/java/io/debezium/connector/cassandra/CassandraConnectorConfigTest.java
https://issues.redhat.com/browse/DBZ-5045
=> DBZ-5045 Remove deprecated FIELD_BLACKLIST config option

.github/workflows/cross-maven.yml, .github/workflows/maven.yml
https://issues.redhat.com/browse/DBZ-5409
=> DBZ-5409 Build stable branches for Cassandra on push/pull event

core/src/main/java/io/debezium/connector/cassandra/CassandraTopicSelector.java
https://issues.redhat.com/browse/DBZ-5457
=> DBZ-5457 Deprecate legacy topic selector for all connectors

README.md
=> DBZ-4839 Debezium is now compatible Cassandra-4

cassandra-3/pom.xml, cassandra-4/pom.xml, pom.xml
DBZ-5640 literal "${project.version}" in the source record instead of the actual version
=> DBZ-5640 literal "${project.version}" in the source record

cassandra-3/src/main/java/io/debezium/connector/cassandra/CassandraConnectorTask.java, cassandra-4/src/main/java/io/debezium/connector/cassandra/CassandraConnectorTask.java, core/src/main/java/io/debezium/connector/cassandra/CassandraConnectorConfig.java, core/src/main/java/io/debezium/connector/cassandra/CassandraConnectorTaskTemplate.java, core/src/test/java/io/debezium/connector/cassandra/AbstractQueueProcessorTest.java, core/src/test/java/io/debezium/connector/cassandra/CassandraConnectorConfigTest.java, core/src/test/java/io/debezium/connector/cassandra/FileOffsetWriterTest.java, core/src/test/java/io/debezium/connector/cassandra/TestUtils.java
https://issues.redhat.com/browse/DBZ-5671
=> DBZ-5671 Remove logic name parameter from sub connector config

cassandra-3/src/main/java/io/debezium/connector/cassandra/CassandraConnectorTask.java, cassandra-3/src/test/java/io/debezium/connector/cassandra/EmbeddedCassandra3ConnectorTestBase.java, cassandra-3/src/test/java/io/debezium/connector/cassandra/QueueProcessorTest.java, cassandra-4/src/main/java/io/debezium/connector/cassandra/CassandraConnectorTask.java, cassandra-4/src/test/java/io/debezium/connector/cassandra/EmbeddedCassandra4ConnectorTestBase.java, cassandra-4/src/test/java/io/debezium/connector/cassandra/QueueProcessorTest.java, core/src/main/java/io/debezium/connector/cassandra/CassandraConnectorConfig.java, core/src/main/java/io/debezium/connector/cassandra/CassandraConnectorTaskTemplate.java, core/src/main/java/io/debezium/connector/cassandra/transforms/CassandraTypeConverter.java, core/src/main/java/io/debezium/connector/cassandra/transforms/CassandraTypeDeserializer.java, core/src/main/java/io/debezium/connector/cassandra/transforms/type/deserializer/VarIntTypeDeserializer.java, core/src/test/java/io/debezium/connector/cassandra/transforms/CassandraTypeConverterTest.java, core/src/test/java/io/debezium/connector/cassandra/transforms/CassandraTypeDeserializerTest.java
https://issues.redhat.com/browse/DBZ-5808
=> DBZ-5808 deserialize BigInteger values from the Cassandra driver

cassandra-4/src/main/java/io/debezium/connector/cassandra/AbstractCassandra4CommitLogParser.java
@ggaborg maybe something to verify that it works for you well?
cc @jpechane
=> DBZ-5776 enqueue EOF event for log file only on successful processing or on error for Cassandra 4 implementation

README.md
@jpechane just approve, I will merge that myself.
=> DBZ-5932 fix version badge in README

core/src/test/java/io/debezium/connector/cassandra/CassandraConnectorTestBase.java
There are properties in Cassandra we can tweak so startup of a node is faster hence tests are faster. As single-node cluster does not need to wait for other nodes to get schema etc we can just set these properties pretty low.
=> DBZ-5933 set properties to Cassandra container to make tests faster

.github/workflows/contributor-check.yml, .github/workflows/cross-maven.yml, .github/workflows/octocat-commits-check.yml, .github/workflows/sanity-check.yml
https://issues.redhat.com/browse/DBZ-5998
=> DBZ-5998 Use correct format for GITHUB_OUTPUT in CI

core/src/main/java/io/debezium/connector/cassandra/transforms/EnvelopeTransformation.java
https://issues.redhat.com/browse/DBZ-7618
=> DBZ-7618 Implement Versioned interfaces in Transformation and Converter plugins

core/src/main/java/io/debezium/connector/cassandra/CassandraConnectorConfig.java
related to: https://github.com/debezium/debezium/pull/5401
=> DBZ-7308 Adapt to core changes

core/src/main/java/io/debezium/connector/cassandra/CassandraConnectorContext.java
relates to: https://github.com/debezium/debezium/pull/5718
=> DBZ-8035 Align core changes

core/src/main/java/io/debezium/connector/cassandra/CassandraOffsetContext.java
related to: https://github.com/debezium/debezium/pull/5938 that must be merged first
=> DBZ-7903 Improve blocking snapshot reliability in case of restart 

cassandra-4/pom.xml, cassandra-4/src/main/java/io/debezium/connector/cassandra/Cassandra4CommitLogSegmentReader.java, cassandra-4/src/main/java/io/debezium/connector/cassandra/Cassandra4SchemaChangeListener.java, cassandra-4/src/main/java/io/debezium/connector/cassandra/CassandraConnectorTask.java, cassandra-4/src/test/java/io/debezium/connector/cassandra/Cassandra4TestProvider.java, cassandra-4/src/test/java/io/debezium/connector/cassandra/transforms/CassandraTypeDeserializerTest.java, pom.xml
by backporting some changes from cassandra5-connector
=> feat: update cassandra4 from 4.0.2 to 4.1.x

core/src/main/java/io/debezium/connector/cassandra/AbstractConnectorTask.java, dse/src/main/java/io/debezium/connector/dse/Dse680ConnectorTask.java
related to: https://github.com/debezium/debezium/pull/6430
=> DBZ-9020 Align to core changes
